---
kind: pipeline
type: docker
name: build
trigger:
  ref:
    - refs/heads/master
    - refs/heads/dev
    - refs/pull/*
    - refs/tags/*
steps:
  - name: install-deps
    image: node
    commands:
      - npm ci
  - name: lint
    image: node
    commands:
      - npm run lint
  - name: build
    image: node
    commands:
      - npm run build
      - cp package.json build
      - cp package-lock.json build
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_passwd
      repo: gergof/matrix-room-deprecation-bot
      autotag: true
      tags:
        - latest
        - ${DRONE_TAG}
    when:
      status:
        - success
      event:
        - tag
---
kind: pipeline
type: ssh
name: deploy
server:
  host:
    from_secret: deploy_host
  user:
    from_secret: deploy_user
  ssh_key:
    from_secret: deploy_key
trigger:
  event:
    - promote
  target:
    - production
steps:
  - name: pull
    commands:
      - docker-compose pull
  - name: recreate
    commands:
      - docker-compose up -d bot-deprecation
---
kind: signature
hmac: 3e2edd21200386719fe6e460d14a9a2d62bd14ff65ddc4bad1cc388e289bf65c

...
